      - db_parkir_hainin
    networks:
      - net_parkir_hainin

  db_parkir_hainin:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: db_parkir_hainin
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: parkir_hainin
      MYSQL_USER: parkir_hainin
      MYSQL_PASSWORD: hainin123
      MYSQL_ROOT_PASSWORD: hainin123
    volumes:
      - db_data_hainin:/var/lib/mysql
      - ./parkir_database.sql:/docker-entrypoint-initdb.d/parkir_database.sql
    networks:
      - net_parkir_hainin

volumes:
  db_data_hainin:

networks:
  net_parkir_hainin:
    driver: bridge
