version: "3.8"

services:

  app_parkir_hainin:
    build: .
    container_name: app_parkir_hainin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db_parkir_hainin
      - DB_DATABASE=parkir_hainin
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db_parkir_hainin
    networks:
      - net_parkir_hainin

  db_parkir_hainin:
    image: mysql:8.0
    container_name: db_parkir_hainin
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: parkir_hainin
      MYSQL_USER: parkir_hainin
      MYSQL_PASSWORD: hainin123
      MYSQL_ROOT_PASSWORD: hainin123
    volumes:
      - db_data_hainin:/var/lib/mysql
      - ./parkir_database.sql:/docker-entrypoint-initdb.d/parkir_database.sql
    networks:
      - net_parkir_hainin

volumes:
  db_data_hainin:

networks:
  net_parkir_hainin:
    driver: bridge
